nixpkgs/default.nix

This is vestigial. It moved to sources.

Prune nixpkgs

---

pins/default-haskell-nix.json

This pulls in https://github.com/input-output-hk/haskell.nix/pull/397 (automatically generate cache for stackage projects).

Update haskell.nix pin

---

ides/vscode.nix

We missed this when hie-bios.nix was renamed in #3.

Fix the vscode derivation

---

overlays/darwin.nix
overlays/default.nix
overlays/patches/x509-system.patch

Would prefer to leverage Unix implementation of x509-system, which will allow people to depend on cacert package.
Alternative would be to hack system to call /usr/bin/system, but that depends on non-pure builds, and can't be managed by nix.
Modifies x509-system to also use NIX_SSL_CERT_FILE env variable instead of SYSTEM_CERTIFICATE_PATH, this matches the rest of nix.

Use Unix implementation of x509-system on Darwin

---

.github/workflows/test.yml
ci.nix

Tries to build nix-tools (which should be responsible for a large part of recompilation when dependencies are bumped).

Add CI with GH Actions

---

.github/workflows/test.yml

Our builds have [started failing](https://github.com/EarnestResearch/er-nix/runs/417885781) on macos-latest.
```
/nix/var/nix/profiles/default/bin/nix-build ci.nix
error: could not set permissions on '/nix/var/nix/profiles/per-user' to 755: Operation not permitted
##[error]Action failed with error: Error: The process '/nix/var/nix/profiles/default/bin/nix-build' failed with exit code 1
```
Suspecting this is a Catalina+Nix problem, though it's not obvious which version the build is running on.  But explicitly downgrading to macos-10.14 solves it for now.

Build on macos-10.14

---

.github/workflows/test.yml

This reverts commit 63c5d3b4e9b3ee81d9de64a977d9e762512dbd75.
Builds are still hanging waiting for macos-latest.  The GitHub Actions blog states that [Mojave was dropped in October](https://github.blog/changelog/2019-10-31-github-actions-macos-virtual-environment-is-updating-to-catalina-and-dropping-mojave-support/), and there is [no mention of support](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/virtual-environments-for-github-hosted-runners#supported-runners-and-hardware-resources) for it now.
The [macos-10.14 build](https://github.com/EarnestResearch/er-nix/runs/418147136#step:4:116) _did_ appear to do something, but it working seems to be accidental.

Revert "Build on macos-10.14"

---

nix/sources.json

Update haskell-nix to the latest version. I'm mostly interested in this to get the latest hackage available.

Bump haskell-nix

---

.github/workflows/test.yml

This version of install-nix-action uses a volume rather than symlink, and should also fix race conditions on build (with MacOS). Building via a symlink was always incorrect, and could build bad derivations.

Update install-nix-action to latest

---

.github/workflows/test.yml

Fixes the intermittent /nix/var/nix/profiles/per-user permission bug on MacOS.

cachix-action@v4

---

overlays/default.nix
overlays/icu.nix

These are now present in lib/system-nixpkgs-map.nix in haskell.nix

Remove icu package aliases

---

nix/sources.nix

(output of running `niv init`)
* Prettify the derivation name in tarballs
The derivation name for package `foo` of type `tarball` is now `foo-src` as opposed to `source`.
* Retire builtin-tarball and builtin-url

Update sources.nix for niv to V18

---

ci.nix

This causes the ghc to be taken from the build platform, rather than from the target platform, this matters for cross-compilation.

Build ghc from pkgs.buildPackages.pkgs.haskell-nix.compiler

---

nix/sources.json

Including:
- move nixpkgs to 20.03
- move haskell.nix to latest
- move pre-commit-hooks to latest, owner from hercules-ci to cachix

Bump all dependencies

---

overlays/default.nix
overlays/ghcide.nix

The branch of ghcide used in haskell-nix fails to work with Template Haskell code on MacOS.

Use master branch of mpickering/ghcide

---

ci.nix

This builds ghcide for supplied ghc versions (continues to build ghc implicitly).

Build ghcide in CI

---

.github/workflows/test.yml
ci-cabal.nix
ci-nix-tools.nix
ci.nix
nix/sources.json

Update packages and CI configuration
Packages are updated to latest.
CI configuration:
- use latest actions
- compile cabal instead of ghcide
(cabal is more generally useful, ghcide users can compile in project CI)
- Rewrite CI definition so that nix-tools is built once per
architecture

Update nix channels and CI configuration

---

nix/sources.json

Fixes one potential issue with extra ghc-options passed to build.
Also includes a big update with ghc 8.10 support.

Update haskell.nix - some fixes, and ghc 8.10 support

---

nix/sources.json

When trying to cross-build from MacOS to Musl, some MacOS flags leaked into flags passed to the musl linker. This cherry-picks an upstream change that hasn't been merged to nixos-20.03 yet.

Fix cross-build from MacOS to other systems

---

applications/upload_docker_to_aws/default.nix
overlays/custom-packages.nix
overlays/patches/skopeo.patch
pkgs/skopeo/default.nix

This is to work around a dumb misleading CD error that is caused by
run-upload-to-aws> DEBU[0035] Ping
https://766386692293.dkr.ecr.us-east-1.amazonaws.com/v2/ err Get
"https://766386692293.dkr.ecr.us-east-1.amazonaws.com/v2/": net/http:
TLS handshake timeout (&url.Error{Op:"Get",
URL:"https://766386692293.dkr.ecr.us-east-1.amazonaws.com/v2/",
Err:http.tlsHandshakeTimeoutError{}})
but looks like
FATA[0044] Error trying to reuse blob
sha256:3ff4f624486be56399049b6aa89fd0eafc14be2d92ce15cfa86355413a281e15
at destination: can't talk to a V1 docker registry
This is the dumb way docker client negotiates registry version.
Master version gives us --retry-times, which may also help in CD.
Patch gives us increased default TLS timeout.
It's unclear atm why the default value is not enough, requires …

Latest skopeo release with a patch

---

overlays/default.nix
overlays/hpack.nix

Puts a version of hpack in `pkgs.haskellPackages` that doesn't require the hash that's causing us merge conflicts in the cabal file on a handful of projects.  Inelegant, but temporary.

Upgrade hpack to 0.34.2

---

overlays/hpack.nix

Overriding hpack causes our ci.nix builds fail building pantry for lack of an hpack >= 0.31.2. :shrug: 
Referring to this new `hpack_0_34` in the project's default.nix, instead of more naturally referring to an overridden one, fixes the problem.

Rename hpack to hpack_0_34

---

default.nix

Creating local overlays is more verbose than it ought to be.  This generalizes `pkgsForSystem`.

`pkgsWith` convenience function

---

tools/haskell-language-server/default.nix

This is heinous.  haskell-language-server has a submodule, which isn't fetched by default, and doesn't contribute to the sha256.  But it doesn't build unless we fetch that submodule.  A similar workaround exists in the upstream nix-hls.
It worked for me because I'd already built directly from nix-hls, and had it cached under that sha256.  I don't think it's going to work for anybody else until we merge this.

Fetch submodule of haskell-language-server

---

README.md
tools/haskell-language-server/default.nix

Reimagines the haskell-language-server tool as a function of the cabal project we're trying to build it for.
I think the reason our template is recompiling a fresh GHC is because nix-hls is explicitly pinned to a hackage index, whereas we're using the default from our haskell.nix.  This aligns things so both the main project and the HLS are on not just the same nominal GHC version, but the same Hackage index.

Parameterize index state of hls

---

nix/sources.json
tools/haskell-language-server/default.nix

nix-hls is instantiating its haskell-nix from one of our haskell-nix's sources' three nixpkgs pins.  We can pick which of the three, but we can't give it our own.  And we've always run haskell-nix with our own nixpkgs pin, so HLS is being built from a different nixpkgs.  
Instead of continuing to accrue hacks to reassemble our sources in the third-party derivation, let's just inline it.  And instead of continuing to speculate, let's test it:
Before:
```
[ross@herbert:~/src/haskell-template]$ nix-store -q -R $(which haskell-language-server) | grep ghc-8.8.3$
/nix/store/pfhrv6llwbri66vq4qg9x5a408qvsgcw-ghc-8.8.3
[ross@herbert:~/src/haskell-template]$ nix-store -q -R $(which ghc) | grep ghc-8.8.3$
/nix/store/z584r6rc2mnws7x43x8khs8lvr6xx96w-ghc-8.8.3
```
After:
``` …
```

Inline nix-hls to make REALLY SURE our packages align

---

.github/workflows/test.yml
README.md
default.nix
test/shell.nix
tools/haskell-language-server/default.nix
tools/haskell-language-server/hls.nix
tools/haskell-language-server/hlsFor.nix

Switch from per-project HLS installations to a set that can be installed with `nix-env` or home-manager.  This is more like the vscode plugin model, but also works nicely in other editors.
By no longer carefully to the project's haskell.nix, we are now reliant on haskell.nix's binary compatibility with same-named GHC versions.  This hasn't been a problem in several months. :crossed_fingers:.

Provide haskell-language-servers for user environments

---

test/shell.nix

haskell-language-server is still struggling to digest aws-cfn-stacks. This gets the latest ghcide in cachix until everyone is migrated.

Cache ghcide-0.4.0

---

.github/workflows/test.yml
.github/workflows/upgrade.yml
README.md

Runs `niv upgrade` and curls the latest LTS into our test our cachix stays primed with modern comforts.  Currently scheduled to run every second and fourth Tuesday.

Upgrade bot

---

.github/workflows/upgrade.yml

The old one was Stack Overflow Certified™ and POSIX compliant, but GitHub Actions has been running it every day this week in spite of the trailing `2`.
This one is boring and might run on weekends but boring crons are good.

Simpler cron expression for upgrades

---

.github/workflows/test.yml
README.md
nix/sources.json

The nixpkgs-20.03 we've been using doesn't work for Big Sur.  20.09 won't, either.  Moving to master should fix it, though it will negatively impact how much we can piggyback off the upstream nix-tools cache.
Dropped the old `nixpkgs-unstable` alias, which was unused, and now equivalent to `nixpkgs`.

Switch to nixpkgs-master

---

pkgs/snowflake-odbc/default.nix

[undmg](https://github.com/matthewbauer/undmg) isn't super-well documented and doesn't seem to have a version number, but anyways after a niv update I stumbled upon this odd behavior when passing a file to it on stdin:
```
% undmg < ~/Downloads/snowflake_odbc_mac-2.22.3.dmg
zsh: segmentation fault  undmg < ~/Downloads/snowflake_odbc_mac-2.22.3.dmg
```
Just using `undmg filename` seems to work fine, though:
```
% undmg ~/Downloads/snowflake_odbc_mac-2.22.3.dmg
% ls
snowflakeODBC.pkg
```
...so this updates the snowflake-odbc package to use the form that doesn't segfault.

Working around undmg segfault

---

nix/sources.json
tools/haskell-language-server/default.nix

Purportedly supports ghc-8.10.3, which we're not caching yet, but that's another bump to consider.

haskell-language-server-0.8.0

---

.github/workflows/test.yml
default.nix

haskell.nix uses its own hackage snapshot unless overridden.
There seems little point in having two snapshots in use, it's a lot more work, especially for simple builds.
Override as per https://github.com/input-output-hk/haskell.nix/blob/master/docs/tutorials/hackage-stackage.md

Only use one hackage snapshot in nix build

---

.github/workflows/test.yml
default.nix
tools/haskell-language-server/default.nix

The latest LTS is 8.10.4, and things are getting creaky on LTS-16.

Support ghc-8.10.4

---

nix/sources.json

Before using these updated versions of `haskell.nix` and `nixpkgs`, I was getting a weird bug that, essentially, base-orphans was trying to build it's haddock docs as part of the build process, and some step was lacking a permission to `cp` in the `/nix/store`. I still don't know the cause, I assume this was a red herring of some other problem, and this error only manifests on my machine. 4 others tested it and 2 tested a "minimal" nix setup that triggered the bug on my machine, and it works on everyone else's machine and... it's just totally inscrutable. I think I won't belabor the point here unless someone's interested.

update haskell.nix and nixpkgs
